export const categoriesData = [
  "OAuth",
  "OIDC",
  "Email",
  // "WebAuthn",
  // "Credentials",
] as const;

export const iconsData: IconDataType[] = [
  {
    id: "school-42-dark",
    name: "School 42 Dark",
    path: "icons/42-school-dark.svg",
    categories: ["OAuth"],
    keywords: ["42", "school", "dark", "oauth"],
    url: "https://www.42.fr/en/",
  },
  {
    id: "school-42-light",
    name: "School 42 Light",
    path: "icons/42-school-light.svg",
    categories: ["OAuth"],
    keywords: ["42", "school", "light", "oauth"],
    url: "https://www.42.fr/en/",
  },
  {
    id: "apple-dark",
    name: "Apple Dark",
    path: "icons/apple-dark.svg",
    categories: ["OAuth"],
    keywords: ["apple", "dark", "oauth"],
    url: "https://www.apple.com/",
  },
  {
    id: "apple-light",
    name: "Apple Light",
    path: "icons/apple-light.svg",
    categories: ["OAuth"],
    keywords: ["apple", "light", "oauth"],
    url: "https://www.apple.com/",
  },
  {
    id: "asgardeo",
    name: "Asgardeo",
    path: "icons/asgardeo.svg",
    categories: ["OAuth"],
    keywords: ["asgardeo", "oauth"],
    url: "https://www.asgardeo.io/",
  },
  {
    id: "auth0",
    name: "Auth0",
    path: "icons/auth0.svg",
    categories: ["OAuth"],
    keywords: ["auth0", "oauth"],
    url: "https://auth0.com/",
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    path: "icons/github-dark.svg",
    categories: ["OAuth"],
    keywords: ["github", "dark", "oauth"],
    url: "https://github.com/",
  },
  {
    id: "github-light",
    name: "GitHub Light",
    path: "icons/github-light.svg",
    categories: ["OAuth"],
    keywords: ["github", "light", "oauth"],
    url: "https://github.com/",
  },
  {
    id: "npm",
    name: "NPM",
    path: "icons/npm.svg",
    categories: ["OAuth"],
    keywords: ["npm", "oauth"],
    url: "https://www.npmjs.com/",
  },
  {
    id: "pnpm-dark",
    name: "Pnpm Dark",
    path: "icons/pnpm-dark.svg",
    categories: ["OAuth"],
    keywords: ["pnpm", "dark", "oauth"],
    url: "https://pnpm.io/",
  },
  {
    id: "pnpm-light",
    name: "Pnpm Light",
    path: "icons/pnpm-light.svg",
    categories: ["OAuth"],
    keywords: ["pnpm", "light", "oauth"],
    url: "https://pnpm.io/",
  },
  {
    id: "authentik",
    name: "Authentik",
    path: "icons/authentik.svg",
    categories: ["OAuth"],
    keywords: ["authentik", "oauth"],
    url: "https://goauthentik.io/",
  },
  {
    id: "azure",
    name: "Azure",
    path: "icons/azure.svg",
    categories: ["OAuth"],
    keywords: ["azure", "oauth"],
    url: "https://azure.microsoft.com",
  },
  {
    id: "bankid-no",
    name: "Bankid No",
    path: "icons/bankid-no.svg",
    categories: ["OAuth"],
    keywords: ["bankid-no", "oauth"],
    url: "https://bankid.no/",
  },
  {
    id: "battlenet",
    name: "Battlenet",
    path: "icons/battlenet.svg",
    categories: ["OAuth"],
    keywords: ["battlenet", "oauth"],
    url: "https://battle.net/",
  },
  {
    id: "beyondidentity",
    name: "Beyondidentity",
    path: "icons/beyondidentity.svg",
    categories: ["OAuth"],
    keywords: ["beyondidentity", "oauth"],
    url: "https://www.beyondidentity.com/",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    path: "icons/bitbucket.svg",
    categories: ["OAuth"],
    keywords: ["bitbucket", "oauth"],
    url: "https://bitbucket.org/",
  },
  {
    id: "box",
    name: "Box",
    path: "icons/box.svg",
    categories: ["OAuth"],
    keywords: ["box", "oauth"],
    url: "https://www.box.com/",
  },
  {
    id: "boxyhq-saml",
    name: "Boxyhq Saml",
    path: "icons/boxyhq-saml.svg",
    categories: ["OAuth"],
    keywords: ["boxyhq-saml", "oauth"],
    url: "https://boxyhq.com/",
  },
  {
    id: "bungie",
    name: "Bungie",
    path: "icons/bungie.svg",
    categories: ["OAuth"],
    keywords: ["bungie", "oauth"],
    url: "https://www.bungie.net/",
  },
  {
    id: "clickup-light-watermark",
    name: "Clickup Light Watermark",
    path: "icons/clickup-light-watermark.svg",
    categories: ["OAuth"],
    keywords: ["clickup-light-watermark", "oauth"],
    url: "https://clickup.com/",
  },
  {
    id: "clickup-dark-watermark",
    name: "Clickup Dark Watermark",
    path: "icons/clickup-dark-watermark.svg",
    categories: ["OAuth"],
    keywords: ["clickup-dark-watermark", "oauth"],
    url: "https://clickup.com/",
  },
  {
    id: "cognito",
    name: "Cognito",
    path: "icons/cognito.svg",
    categories: ["OAuth"],
    keywords: ["cognito", "oauth"],
    url: "https://aws.amazon.com/cognito/",
  },
  {
    id: "coinbase",
    name: "coinbase",
    path: "icons/coinbase.svg",
    categories: ["OAuth"],
    keywords: ["coinbase", "oauth"],
    url: "https://www.coinbase.com/",
  },
  {
    id: "descope",
    name: "Descope",
    path: "icons/descope.svg",
    categories: ["OAuth"],
    keywords: ["descope", "oauth"],
    url: "https://www.descope.com/",
  },
  {
    id: "discord",
    name: "Discord",
    path: "icons/discord.svg",
    categories: ["OAuth"],
    keywords: ["discord", "oauth"],
    url: "https://discord.com/",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    path: "icons/dribbble.svg",
    categories: ["OAuth"],
    keywords: ["dribbble", "oauth"],
    url: "https://dribbble.com/",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    path: "icons/dropbox.svg",
    categories: ["OAuth"],
    keywords: ["dropbox", "oauth"],
    url: "https://www.dropbox.com/",
  },
  {
    id: "duende-identity-dark",
    name: "Duende Identity Dark",
    path: "icons/duende-identity-dark.svg",
    categories: ["OAuth"],
    keywords: ["duende-identity-dark", "oauth"],
    url: "https://duendesoftware.com/products/identityserver",
  },
  {
    id: "duende-identity-light",
    name: "Duende Identity Light",
    path: "icons/duende-identity-light.svg",
    categories: ["OAuth"],
    keywords: ["duende-identity-light", "oauth"],
    url: "https://duendesoftware.com/products/identityserver",
  },
  {
    id: "eveonline",
    name: "Eve Online",
    path: "icons/eveonline.svg",
    categories: ["OAuth"],
    keywords: ["eveonline", "oauth"],
    url: "https://www.eveonline.com/",
  },
  {
    id: "facebook",
    name: "Facebook",
    path: "icons/facebook.svg",
    categories: ["OAuth"],
    keywords: ["facebook", "oauth"],
    url: "https://www.facebook.com/",
  },
  {
    id: "faceit",
    name: "Faceit",
    path: "icons/faceit.svg",
    categories: ["OAuth"],
    keywords: ["faceit", "oauth"],
    url: "https://www.faceit.com/",
  },
  {
    id: "figma",
    name: "figma",
    path: "icons/figma.svg",
    categories: ["OAuth"],
    keywords: ["figma", "oauth"],
    url: "https://www.figma.com/",
  },
  {
    id: "forwardemail",
    name: "Forward Email",
    path: "icons/forwardemail.svg",
    categories: ["Email"],
    keywords: ["forwardemail", "oauth"],
    url: "https://forwardemail.net/",
  },
  {
    id: "foursquare",
    name: "Foursquare",
    path: "icons/foursquare.svg",
    categories: ["OAuth"],
    keywords: ["foursquare", "oauth"],
    url: "https://foursquare.com/",
  },
  {
    id: "freshbooks",
    name: "Freshbooks",
    path: "icons/freshbooks.svg",
    categories: ["OAuth"],
    keywords: ["freshbooks", "oauth"],
    url: "https://www.freshbooks.com/",
  },
  {
    id: "frontegg",
    name: "Frontegg",
    path: "icons/frontegg.svg",
    categories: ["OAuth"],
    keywords: ["frontegg", "oauth"],
    url: "https://frontegg.com/",
  },
  {
    id: "fusionauth-dark",
    name: "Fusionauth Dark",
    path: "icons/fusionauth-dark.svg",
    categories: ["OAuth"],
    keywords: ["fusionauth-dark", "oauth"],
    url: "https://fusionauth.io/",
  },
  {
    id: "fusionauth-light",
    name: "Fusionauth Light",
    path: "icons/fusionauth-light.svg",
    categories: ["OAuth"],
    keywords: ["fusionauth-light", "oauth"],
    url: "https://fusionauth.io/",
  },
  {
    id: "gitlab",
    name: "Gitlab",
    path: "icons/gitlab.svg",
    categories: ["OAuth"],
    keywords: ["gitlab", "oauth"],
    url: "https://gitlab.com/",
  },
  {
    id: "google",
    name: "Google",
    path: "icons/google.svg",
    categories: ["OAuth"],
    keywords: ["google", "oauth"],
    url: "https://google.com/",
  },
  {
    id: "hubspot",
    name: "Hubspot",
    path: "icons/hubspot.svg",
    categories: ["OAuth"],
    keywords: ["hubspot", "oauth"],
    url: "https://www.hubspot.com/",
  },
  {
    id: "identity-server4",
    name: "Identity Server 4",
    path: "icons/identity-server4.svg",
    categories: ["OAuth"],
    keywords: ["identity-server4", "oauth"],
    url: "https://identityserver4.readthedocs.io/",
  },
  {
    id: "instagram",
    name: "Instagram",
    path: "icons/instagram.svg",
    categories: ["OAuth"],
    keywords: ["instagram", "oauth"],
    url: "https://instagram.com/",
  },
  {
    id: "kakao",
    name: "Kakao",
    path: "icons/kakao.svg",
    categories: ["OAuth"],
    keywords: ["kakao", "oauth"],
    url: "https://www.kakao.com/",
  },
  {
    id: "keycloak",
    name: "Keycloak",
    path: "icons/keycloak.svg",
    categories: ["OAuth"],
    keywords: ["keycloak", "oauth"],
    url: "https://www.keycloak.org/",
  },
  {
    id: "line",
    name: "Line",
    path: "icons/line.svg",
    categories: ["OAuth"],
    keywords: ["line", "oauth"],
    url: "https://www.line.me/",
  },
  {
    id: "linkedin",
    name: "Linkedin",
    path: "icons/linkedin.svg",
    categories: ["OAuth"],
    keywords: ["linkedin", "oauth"],
    url: "https://www.linkedin.com/",
  },
  {
    id: "logto-dark",
    name: "Logto Dark",
    path: "icons/logto-dark.svg",
    categories: ["OAuth"],
    keywords: ["logto", "dark", "oauth"],
    url: "https://logto.io/",
  },
  {
    id: "logto-light",
    name: "Logto Light",
    path: "icons/logto-light.svg",
    categories: ["OAuth"],
    keywords: ["logto", "light", "oauth"],
    url: "https://logto.io/",
  },
  {
    id: "loops",
    name: "Loops",
    path: "icons/loops.svg",
    categories: ["OAuth"],
    keywords: ["loops", "oauth"],
    url: "https://www.loops.so/",
  },
  {
    id: "mailchimp",
    name: "mailchimp",
    path: "icons/mailchimp.svg",
    categories: ["OAuth"],
    keywords: ["mailchimp", "oauth"],
    url: "https://www.mailchimp.com/",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    path: "icons/mailgun.svg",
    categories: ["OAuth"],
    keywords: ["mailgun", "oauth"],
    url: "https://www.mailgun.com/",
  },
  {
    id: "mailru",
    name: "Mailru",
    path: "icons/mailru.svg",
    categories: ["OAuth"],
    keywords: ["mailru", "oauth"],
    url: "https://mail.ru/",
  },
  {
    id: "mastodon",
    name: "Mastodon",
    path: "icons/mastodon.svg",
    categories: ["OAuth"],
    keywords: ["mastodon", "oauth"],
    url: "https://www.joinmastodon.org",
  },
  {
    id: "mattermost",
    name: "Mattermost",
    path: "icons/mattermost.svg",
    categories: ["OAuth"],
    keywords: ["mattermost", "oauth"],
    url: "https://mattermost.com/",
  },
  {
    id: "medium-dark",
    name: "Medium Dark",
    path: "icons/medium-dark.svg",
    categories: ["OAuth"],
    keywords: ["medium", "dark", "oauth"],
    url: "https://medium.com/",
  },
  {
    id: "medium-light",
    name: "Medium Light",
    path: "icons/medium-light.svg",
    categories: ["OAuth"],
    keywords: ["medium", "light", "oauth"],
    url: "https://medium.com/",
  },
  {
    id: "microsoft-entra-id",
    name: "Microsoft Entra ID",
    path: "icons/microsoft-entra-id.svg",
    categories: ["OAuth"],
    keywords: ["microsoft-entra-id", "oauth"],
    url: "https://www.microsoft.com/en-in/security/business/microsoft-entra",
  },
  {
    id: "naver",
    name: "Naver",
    path: "icons/naver.svg",
    categories: ["OAuth"],
    keywords: ["naver", "oauth"],
    url: "https://www.naver.com/",
  },
  {
    id: "netlify",
    name: "Netlify",
    path: "icons/netlify.svg",
    categories: ["OAuth"],
    keywords: ["netlify", "oauth"],
    url: "https://www.netlify.com/",
  },
  {
    id: "netsuite",
    name: "Netsuite",
    path: "icons/netsuite.svg",
    categories: ["OAuth"],
    keywords: ["netsuite", "oauth"],
    url: "https://www.netsuite.com/",
  },
  {
    id: "nextcloud",
    name: "Nextcloud",
    path: "icons/nextcloud.svg",
    categories: ["OAuth"],
    keywords: ["nextcloud", "oauth"],
    url: "https://www.nextcloud.com/",
  },
  {
    id: "nodemailer",
    name: "Nodemailer",
    path: "icons/nodemailer.svg",
    categories: ["Email"],
    keywords: ["nodemailer", "oauth"],
    url: "https://www.nodemailer.com/",
  },
  {
    id: "notion",
    name: "Notion",
    path: "icons/notion.svg",
    categories: ["OAuth"],
    keywords: ["notion", "oauth"],
    url: "https://www.notion.com/",
  },
];

export type Category = (typeof categoriesData)[number];

export interface IconDataType {
  id: string;
  name: string;
  path: string;
  categories: Category[];
  keywords: string[];
  url: string;
}
