export const categoriesData = [
  "OAuth",
  "OIDC",
  "WebAuthn",
  "Email",
  "Credentials",
] as const;

export const iconsData: IconDataType[] = [
  {
    id: "school-42-dark",
    name: "School 42 Dark",
    path: "icons/42-school-dark.svg",
    categories: ["OAuth"],
    keywords: ["42", "school", "dark", "oauth"],
    url: "https://www.42.fr/en/",
  },
  {
    id: "school-42-light",
    name: "School 42 Light",
    path: "icons/42-school-light.svg",
    categories: ["OAuth"],
    keywords: ["42", "school", "light", "oauth"],
    url: "https://www.42.fr/en/",
  },
  {
    id: "apple-dark",
    name: "Apple Dark",
    path: "icons/apple-dark.svg",
    categories: ["OAuth"],
    keywords: ["apple", "dark", "oauth"],
    url: "https://www.apple.com/",
  },
  {
    id: "apple-light",
    name: "Apple Light",
    path: "icons/apple-light.svg",
    categories: ["OAuth"],
    keywords: ["apple", "light", "oauth"],
    url: "https://www.apple.com/",
  },
  {
    id: "auth0",
    name: "Auth0",
    path: "icons/auth0.svg",
    categories: ["OAuth"],
    keywords: ["auth0", "oauth"],
    url: "https://auth0.com/",
  },
  {
    id: "asgardeo",
    name: "Asgardeo",
    path: "icons/asgardeo.svg",
    categories: ["OAuth"],
    keywords: ["asgardeo", "oauth"],
    url: "https://www.asgardeo.io/",
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    path: "icons/github-dark.svg",
    categories: ["OAuth"],
    keywords: ["github", "dark", "oauth"],
    url: "https://github.com/",
  },
  {
    id: "github-light",
    name: "GitHub Light",
    path: "icons/github-light.svg",
    categories: ["OAuth"],
    keywords: ["github", "light", "oauth"],
    url: "https://github.com/",
  },
  {
    id: "npm",
    name: "NPM",
    path: "icons/npm.svg",
    categories: ["OAuth"],
    keywords: ["npm", "oauth"],
    url: "https://www.npmjs.com/",
  },
  {
    id: "pnpm-dark",
    name: "Pnpm Dark",
    path: "icons/pnpm-dark.svg",
    categories: ["OAuth"],
    keywords: ["pnpm", "dark", "oauth"],
    url: "https://pnpm.io/",
  },
  {
    id: "pnpm-light",
    name: "Pnpm Light",
    path: "icons/pnpm-light.svg",
    categories: ["OAuth"],
    keywords: ["pnpm", "light", "oauth"],
    url: "https://pnpm.io/",
  },
  {
    id: "authentik",
    name: "Authentik",
    path: "icons/authentik.svg",
    categories: ["OAuth"],
    keywords: ["authentik", "oauth"],
    url: "https://goauthentik.io/",
  },
  {
    id: "azure",
    name: "Azure",
    path: "icons/azure.svg",
    categories: ["OAuth"],
    keywords: ["azure", "oauth"],
    url: "https://azure.microsoft.com",
  },
  {
    id: "bankid-no",
    name: "Bankid No",
    path: "icons/bankid-no.svg",
    categories: ["OAuth"],
    keywords: ["bankid-no", "oauth"],
    url: "https://bankid.no/",
  },
  {
    id: "battle-net",
    name: "Battlenet",
    path: "icons/battlenet.svg",
    categories: ["OAuth"],
    keywords: ["battlenet", "oauth"],
    url: "https://battle.net/",
  },
  {
    id: "beyondidentity",
    name: "Beyondidentity",
    path: "icons/beyondidentity.svg",
    categories: ["OAuth"],
    keywords: ["beyondidentity", "oauth"],
    url: "https://www.beyondidentity.com/",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    path: "icons/bitbucket.svg",
    categories: ["OAuth"],
    keywords: ["bitbucket", "oauth"],
    url: "https://bitbucket.org/",
  },
  {
    id: "box",
    name: "Box",
    path: "icons/box.svg",
    categories: ["OAuth"],
    keywords: ["box", "oauth"],
    url: "https://www.box.com/",
  },
  {
    id: "boxyhq-saml",
    name: "Boxyhq Saml",
    path: "icons/boxyhq-saml.svg",
    categories: ["OAuth"],
    keywords: ["boxyhq-saml", "oauth"],
    url: "https://boxyhq.com/",
  },
  {
    id: "bungie",
    name: "Bungie",
    path: "icons/bungie.svg",
    categories: ["OAuth"],
    keywords: ["bungie", "oauth"],
    url: "https://www.bungie.net/",
  },
  {
    id: "cognito",
    name: "Cognito",
    path: "icons/cognito.svg",
    categories: ["OAuth"],
    keywords: ["cognito", "oauth"],
    url: "https://aws.amazon.com/cognito/",
  },
  {
    id: "clickup-dark-watermark",
    name: "Clickup Dark Watermark",
    path: "icons/clickup-dark-watermark.svg",
    categories: ["OAuth"],
    keywords: ["clickup-dark-watermark", "oauth"],
    url: "https://clickup.com/",
  },
  {
    id: "clickup-dark-watermark",
    name: "Clickup Dark Watermark",
    path: "icons/clickup-dark-watermark.svg",
    categories: ["OAuth"],
    keywords: ["clickup-dark-watermark", "oauth"],
    url: "https://clickup.com/",
  },
];

export type Category = (typeof categoriesData)[number];

export interface IconDataType {
  id: string;
  name: string;
  path: string;
  categories: Category[];
  keywords: string[];
  url: string;
}
